version: '3'

services:
  app:
    image: node:lts # バージョン指定も可能 ex. node:12.16.1
    container_name: lesson-backend-node
    tty: true
    # ホスト側のポート:コンテナのポート
    ports:
      - '8000:8000'
    #（ホスト側の./srcをコンテナの/appにマウント）
    volumes:
      - ./:/app
    # 起動時のカレントフォルダを指定
    working_dir: '/app'

    # 起動後に実行するコマンドを指定
    command: npm start
